# Generated by Django 4.0.4 on 2022-05-25 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc_probs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegralQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integrand', models.CharField(max_length=200)),
                ('technique', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='answer_text',
            new_name='user_answer',
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc_probs.integralquestion'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
