# Generated by Django 4.0.4 on 2022-05-26 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc_probs', '0004_useranswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='user_answer',
            new_name='user_answer_text',
        ),
    ]
