# Generated by Django 4.0.5 on 2022-06-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_probs', '0006_delete_useranswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaterIntegralQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integrand', models.CharField(max_length=200)),
                ('technique', models.CharField(max_length=200)),
            ],
        ),
    ]
