# Generated by Django 4.0.6 on 2022-08-01 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc_probs', '0007_laterintegralquestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LaterIntegralQuestion',
        ),
    ]
